### ISSUE TITLE
Fails to load JavaFX application

### ISSUE THREAD

**Issue by aalmiray** [mikehearn/graviton-browser#34]
Go the following error when attempting to load a locally deployed Griffon JavaFX application

    2018-10-05 10:44:01 INFO [JavaFX Application Thread] HistoryManager.<init>()
    Graviton cache is /Users/aalmiray/Library/Caches/Graviton Browser
    2018-10-05 10:44:01 INFO [JavaFX Application Thread] HistoryManager.<init>()
    Read 1 entries from the history list
    2018-10-05 10:44:06 INFO [Thread-9] HistoryManager.search()
    Searching for a cached resolution in our history list for 'com.acme:login:1.0.0'
    2018-10-05 10:44:06 INFO [Thread-9] AppLauncher.start()
    Used previously resolved coordinates com.acme:login:1.0.0 -> com.acme:login:jar:1.0.0 @ 2018-10-05T08:38:13.999Z (1 cp entries)
    2018-10-05 10:44:06 INFO [Thread-9] AppLauncher.start()
    App name: login
    2018-10-05 10:44:06 INFO [Thread-9] AppLauncher.start()
    App description: null
    2018-10-05 10:44:06 INFO [Thread-9] HistoryManager.recordHistoryEntry()
    Recording history entry: com.acme:login:1.0.0 -> com.acme:login:jar:1.0.0 @ 2018-10-05T08:44:06.102Z (1 cp entries)
    2018-10-05 10:44:06 INFO [Thread-9] AppLauncher.start()
    Searching for a JavaFX main class took 0.2 seconds
    2018-10-05 10:44:06 INFO [Thread-9] AppLauncher.start()
    JavaFX Application class found: class griffon.javafx.AbstractJavaFXGriffonApplication
    2018-10-05 10:44:06 ERROR [JavaFX Application Thread] SLF4JBridgeHandler.callPlainSLF4JLogger()
    Uncaught error: java.security.PrivilegedActionException
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    Caused by: java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at net.plan99.graviton.AppLauncher$invokeJavaFXApplication$1.invoke(AppLauncher.kt:175)
        at net.plan99.graviton.AppLauncher$invokeJavaFXApplication$1.invoke(AppLauncher.kt:24)
        at net.plan99.graviton.UtilsKt$sam$java_lang_Runnable$0.run(Utils.kt)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

The problem occurs because the class `griffon.javafx.AbstractJavaFXGriffonApplication` is an abstract class. The concrete class is `griffon.javafx.JavaFXGriffonApplication`. More over, the jar file contains the following manifest entry which is ignored

    Main-Class: org.kordamp.griffon.examples.login.Launcher

Test application code available at https://github.com/aalmiray/griffon-examples/tree/master/login
Steps to build and deploy

 1. git clone https://github.com/aalmiray/griffon-examples.git
 2. cd griffon-examples/login
 3. ./gradlew shadowJar
 4. mkdir -p ~/.m2/dev/local/com/acme/login/1.0.0
 5. cp login/build/libs/login-example-0.1.0-SNAPSHOT-all.jar ~/.m2/dev-local/com/acme/login/1.0.0/login-1.0.0.jar
 6. touch ~/.m2/dev-local/com/acme/login/1.0.0/login-1.0.0.pom

The contents of the POM file should be

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <modelVersion>4.0.0</modelVersion>
        <groupId>con.acme</groupId>
        <artifactId>acme</artifactId>
        <version>1.0.0</version>
    </project>

**Comment by aalmiray** [comment]
Two issues stem from this problem:

1. The search mechanism for a suitable JavaFX application class must find the *first* concrete implementation, that is, skip abstract classes.
2. Use the `Main-Class` attribute found in a Manifest is ignored.

There's code in `AppLoadResult` that reads the manifest entry but it's not used as Graviton attempts to load a JavaFX compatible `Application` class first. IMHO It should honor the manifest entry regardless. If there's no manifest entry then it may try to search for a compatible JavaFX application class.

**Comment by mikehearn** [comment]
Thanks, I'm reworking startup at the moment actually and this is something I already fixed (but the work isn't committed yet).

What's the right way for me to replicate your test? I'll make sure your app works.

**Comment by mikehearn** [comment]
Oh, sorry, apparently I'm blind. You already provided me that information. I'll get on it.

**Comment by mikehearn** [comment]
This is fixed now.

I modified the sample gradle file to install to the dev-local repository. Here's the diff:

```
diff --git a/login/build.gradle b/login/build.gradle
index 13ebcbb..e7f7d98 100644
--- a/login/build.gradle
+++ b/login/build.gradle
@@ -24,6 +24,7 @@ apply plugin: 'groovy'
 apply plugin: 'org.codehaus.griffon.griffon'
 apply plugin: 'net.nemerosa.versioning'
 apply plugin: 'net.ltgt.apt'
+apply plugin: 'maven-publish'
 
 Date buildTimeAndDate = new Date()
 ext {
@@ -119,8 +120,34 @@ shadowJar {
             'META-INF/editors/java.beans.PropertyEditor'
         ]
     }
+
+    classifier = null
 }
 
+publishing {
+    publications {
+        maven(MavenPublication) {
+            groupId = 'com.acme'
+            artifactId = 'login'
+            version = '1.0'
+
+            artifact shadowJar
+
+            pom {
+                name = 'Griffon framework login sample'
+                description = 'Demonstrates various features of the Griffon framework.'
+            }
+        }
+    }
+
+    repositories {
+        maven {
+            url = "${System.properties['user.home']}/.m2/dev-local"
+        }
+    }
+}
+
+
 startScripts {
     doLast {
         if (!macosx) unixScript.text = unixScript.text.replaceAll('"(-Xdock:(name|icon)=)([^"]*?)(")', ' ')
```

**Comment by aalmiray** [comment]
It works now, than you! You also solved the problem of calling `Application.launch()` more than once which I was having when attempted to hack a workaround. Also, I now know the answer to what happens when the application quits, the browser comes up again, nice.
